//! Procedural macros for mamalluca metric collectors.
//!
//! Provides the `#[collector]` attribute macro that generates boilerplate
//! constants and `inventory` registration for `MetricCollector` implementations.
//!
//! # Usage
//!
//! ```ignore
//! use mamalluca_macros::collector;
//!
//! #[collector(prefix = "fan")]
//! pub struct FanCollector;
//!
//! #[collector(prefix = "tmc2209", named)]
//! pub struct Tmc2209Collector;
//! ```

use proc_macro::TokenStream;
use quote::quote;
use syn::{DeriveInput, LitStr, parse_macro_input};

/// Marks a struct as a metric collector and registers it with the global registry.
///
/// This attribute macro generates:
/// - `KEY_PREFIX: &'static str` — the Moonraker status key prefix this collector handles
/// - `IS_NAMED: bool` — whether this collector handles named instances (e.g. `tmc2209 stepper_x`)
/// - An `inventory::submit!` call that auto-registers the collector at startup
///
/// The user must still manually implement `MetricCollector` for the struct, but can
/// delegate `key_prefix()` and `is_named()` to the generated constants:
///
/// ```ignore
/// impl MetricCollector for FanCollector {
///     fn key_prefix(&self) -> &'static str { Self::KEY_PREFIX }
///     fn is_named(&self) -> bool { Self::IS_NAMED }
///     fn record(&self, key: &str, name: Option<&str>, data: &serde_json::Value) -> anyhow::Result<()> {
///         // ...
///     }
/// }
/// ```
///
/// # Attributes
///
/// - `prefix = "..."` (required) — the Moonraker status key prefix
/// - `named` (optional flag) — set `IS_NAMED` to `true` for named-instance collectors
///
/// # Errors
///
/// Produces a compile error if:
/// - The `prefix` attribute is missing
/// - An unrecognized attribute is provided
#[proc_macro_attribute]
pub fn collector(attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as DeriveInput);
    let struct_name = &input.ident;

    // Parse the macro attributes: `prefix = "..."` and optional `named` flag.
    let mut prefix: Option<String> = None;
    let mut named = false;

    // `syn::meta::parser` provides a callback-based parser for meta items.
    // Each call to the closure handles one attribute key-value pair or flag.
    let parser = syn::meta::parser(|meta| {
        if meta.path.is_ident("prefix") {
            // `meta.value()` consumes the `=` token and returns the value parser.
            let value: LitStr = meta.value()?.parse()?;
            prefix = Some(value.value());
            Ok(())
        } else if meta.path.is_ident("named") {
            named = true;
            Ok(())
        } else {
            Err(meta.error("expected `prefix = \"...\"` or `named`"))
        }
    });

    parse_macro_input!(attr with parser);

    // The `prefix` attribute is required — emit a compile error if missing.
    let Some(prefix_value) = prefix else {
        return syn::Error::new_spanned(&input.ident, "#[collector] requires `prefix = \"...\"`")
            .to_compile_error()
            .into();
    };

    // Generate the struct definition (passthrough), associated constants, and
    // inventory registration. The `::inventory::submit!` macro and
    // `crate::metrics::CollectorEntry` resolve in the *calling* crate's scope,
    // not in this proc-macro crate.
    let expanded = quote! {
        #input

        impl #struct_name {
            /// Status key prefix for Moonraker subscriptions.
            /// Auto-generated by the `#[collector]` attribute macro.
            pub const KEY_PREFIX: &'static str = #prefix_value;

            /// Whether this collector handles named instances (e.g. `tmc2209 stepper_x`).
            /// Auto-generated by the `#[collector]` attribute macro.
            pub const IS_NAMED: bool = #named;
        }

        // Auto-register this collector with the global registry at program startup.
        // `inventory` uses platform-specific linker tricks to collect all submissions
        // without requiring a central registration function.
        ::inventory::submit! {
            crate::metrics::CollectorEntry::new(#struct_name)
        }
    };

    expanded.into()
}
